name: Test workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test sudokuku
    defaults:
      run:
        working-directory: ./src/sudokuku
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -W ignore -m pip install --upgrade pip
        python -W ignore -m pip install -U codecov pytest-cov
        python -W ignore -m pip install -r requirements.txt
        python -W ignore -m pip install -r requirements-dev.txt
    - name: Run tests and collect coverage
      run: py -m pytest
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
